debug-mode: false    #Print debug information in the console

#         Messages to display to staff members when their shift starts or ends           #
################################################

shift-end-afk-message: "&4Your shift has been automatically ended because you went afk! Hours This Month: %staff_timesheet_current_hours%. Your Monthly Goal: %staff_timesheet_monthly_goal%. You're %staff_hours_completed_percentage% of the way there!"
shift-end-clockout-message: "&a Shift ended. Your time has been logged! Hours This Month: %staff_timesheet_current_hours%. Your Monthly Goal: %staff_timesheet_monthly_goal%. You're %staff_hours_completed_percentage% of the way there!"
shift-start-message: "&aYour shift has started. Your time is being logged!"




#                                 Shift end labels for use in the staff logbooks                                     #
################################################

shift-end-label-afk: "[&4AFK]"
shift-end-label-disconnected: "[&4Disconnected]"
shift-end-label-clockout: "[&4Clocked Out]"
shift-end-plugin-disabled: "[&4Plugin Disabled]"



  
#                                                           Staff Members                                                                        #
#                Use the following example format to define a staff memeber                   #
#   You can use http://mcuuid.net/ to determine player uuids by player name     #
################################################

#Example Staff Member Config Format#

staff-members:                                                                                                   #List of staff member configurations

  #Example Staff Member Config Format - Add staff members to the 'staff-members' list with the following example's format
  Kloudy:                                                                                                                 #Staff member player name
    uuid: "b8a93b92-fab4-4906-b71d-309a051fb2d7"                       #Staff member uuid
    super-admin: true                                                                                          #(Default: false) (true or false) if the staff member is a super admin
    clock-in-permission: "mystaff.permission"                                       #(Default: none) pex permission group to place the staff member in during their shift. This permission is removed from the staff member when they clock out.
    time-goal: "15:00:00"                                                               #Monthly time goal for the staff member. Time format: "hh:mm:ss
    rank-title: "Junior Mod"                                                                               #(Default: none) Name of staff member's rank
    logged-time: "00:00:00"                                                 #(Default: 0) Hours the staff member has logged this month. The plugin will update this value as they log hours, but you can override that amount and place in a different value. Time format: "hh:mm:ss                                                      




#                                                                 Error Messages                                                                 #
################################################

error-message-negative-time: "&4Removing this much time will cause this staff member to have negative hours! Please don't remove more time than this staff member has already logged."
error-message-not-staff: "&4You are not part of the staff members list!"             #Displayed to the player if they attempt /staff shift start but they are not configured under the 'staff-members' section of the config
error-message-not-clocked-in: "&4You are not currently clocked in!"                    #Displayed if a player tries to use /staff shift end but they are not currently on the clock

